language: c

os: linux
dist: trusty


compiler: arm-none-eabi-gcc


before_install:
  -  sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
  -  sudo apt-get update -q
  -  sudo apt-get install gcc-arm-embedded -y


script:
  -  cd targets/Cloud_STM32F429IGTx_FIRE/GCC
  -  make

before_deploy:
  - zip -r build.zip build

deploy:
  provider: releases
  api_key: $USERTOKEN
  skip_cleanup: true
  file:
    - build.zip
  on:
    tags: true
    all_branches: true

